sudo: required
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - 8

env:
  global:
    - secure: ""
  
  matrix:
    - PACKAGE=styles
    - PACKAGE=angular
    - PACKAGE=vue
  
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd packages/$PACKAGE

script:
  cat package.json