sudo: required
dist: trusty

language: node_js
node_js:
  - 10.9

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

stages:
  - bootstrap
  - styles
  - deploy

deployNpm: &deployNpm
  deploy:
    provider: npm
    email: mshickman91@gmail.com
    api_key: $NPM_TOKEN
      # secure: "d7808845-f528-473a-81d1-da18151438cb"
    on:
      branch:
        - master
        - vue3
    skip_cleanup: true

deployStuff: &deployStuff
  addons:
    chrome: stable

  before_install:
    - npm install -g lerna
  install: lerna bootstrap
  before_script: cd packages/$PACKAGE
  script:
    - npm run test
    - npm run build
  before_deploy:
    - cd dist
  <<: *deployNpm
      

jobs:
  include:
    # - stage: bootstrap
    #   env: PACKAGE="boobstrap"
    #   script:
    #     - npm install -g lerna
    #     - lerna bootstrap

    - stage: styles
      env: PACKAGE=styles
      script: cd packages/$PACKAGE
      <<: *deployNpm

    - stage: deploy
      env: PACKAGE=angular
      <<: *deployStuff
    
    - stage: deploy
      env: PACKAGE=vue
      <<: *deployStuff